export const lightTheme = {
  body: 'var(--color-white)',
  border: 'var(--color-border)',
  grayParagraph: 'var(--color-border)',
  text: 'var(--color-black)',
  textPopup: 'var(--color-black)',
  borderTab: 'var(--color-gray)',
  popupBackground: 'var(--color-white)',
  popupClose: 'var(--color-light-gray)',
  inputBackGround: 'var(--color-light-gray)',
  detailsBackGround: 'var(--color-light-gray)',
  inputPlaceholder: 'var(--color-gray)',
  searchPlaceholder: 'var(--color-black)',
  accent: 'var(--color-accent)',
  jobText: 'var(--color-dark-gray)',
};
export const darkTheme = {
  body: 'var(--color-primary)',
  border: 'var(--color-white)',
  grayParagraph: 'var(--color-border)',
  text: 'var(--color-light)',
  textPopup: 'var(--color-black)',
  borderTab: 'var(--color-gray)',
  popupBackground: 'var(--color-gray)',
  popupClose: 'var(--color-light)',
  inputPlaceholder: 'var(--color-gray)',
  detailsBackGround: 'var(--color-dark-gray)',
  searchPlaceholder: 'var(--color-black)',
  accent: 'var(--color-accent)',
  jobText: 'var(--color-dark-gray)',
  inputBackGround: 'var(--color-light-gray)',
};
