export enum Departments {
  all = 'all',
  android = 'android',
  ios = 'ios',
  design = 'design',
  management = 'management',
  qa = 'qa',
  back_office = 'back_office',
  frontend = 'frontend',
  hr = 'hr',
  pr = 'pr',
  backend = 'backend',
  support = 'support',
  analytics = 'analytics',
}
